apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
  annotations:
    tenxcloud.com/schemaPortname: wordpress-1/TCP
spec:
  ports:
    - name: wordpress-1
      protocol: TCP
      targetPort: 80
      port: 80
  selector:
    app: wordpress
  externalIPs:
    - 11.11.1.1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress:4.8.0-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          value: admin
        ports:
        - containerPort: 80
          name: wordpress-1
